import express from "express";
import fs from "fs";
import cloudinary from "../config/cloudinary.js";
import UserPdf from "../models/UserPdf.js";

const router = express.Router();

const normalizePdfRecord = (record) => {
  const pdf = record.toObject ? record.toObject() : record;

  const sourceUrl = pdf.imageUrl || pdf.pdfUrl;
  if (!sourceUrl) return pdf;

  const cleanedUrl = sourceUrl.replace("fl_attachment:false/", "");
  const derivedDownloadUrl = cleanedUrl.includes("/upload/")
    ? cleanedUrl.replace("/upload/", "/upload/fl_attachment/")
    : cleanedUrl;

  return {
    ...pdf,
    imageUrl: pdf.imageUrl || cleanedUrl,
    pdfUrl: pdf.pdfUrl || cleanedUrl,
    downloadUrl: pdf.downloadUrl || derivedDownloadUrl,
  };
};

router.post("/generate", async (req, res) => {
  try { 
    const { name, email } = req.body;

    const filePath = `./temp_${Date.now()}.svg`;
    const safeName = (name || "").replace(/[<>&'"]/g, "");
    const safeEmail = (email || "").replace(/[<>&'"]/g, "");
    const svg = `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630" viewBox="0 0 1200 630">
  <rect width="1200" height="630" fill="#0f172a"/>
  <rect x="40" y="40" width="1120" height="550" rx="24" fill="#111827" stroke="#334155" stroke-width="2"/>
  <text x="80" y="150" fill="#e2e8f0" font-size="52" font-family="Arial, sans-serif" font-weight="700">User Information</text>
  <text x="80" y="260" fill="#93c5fd" font-size="38" font-family="Arial, sans-serif">Name: ${safeName}</text>
  <text x="80" y="330" fill="#a7f3d0" font-size="38" font-family="Arial, sans-serif">Email: ${safeEmail}</text>
  <text x="80" y="560" fill="#94a3b8" font-size="24" font-family="Arial, sans-serif">Generated by Image Generator App</text>
</svg>`;

    fs.writeFileSync(filePath, svg, "utf8");

    try {
      const result = await cloudinary.uploader.upload(filePath, {
        resource_type: "image",
        type: "upload",
      });

      const imageUrl = cloudinary.url(result.public_id, {
        resource_type: "image",
        type: "upload",
        format: "png",
        secure: true,
      });

      const downloadUrl = cloudinary.url(result.public_id, {
        resource_type: "image",
        type: "upload",
        format: "png",
        secure: true,
        flags: "attachment",
      });

      if (fs.existsSync(filePath)) fs.unlinkSync(filePath);

      const saved = await UserPdf.create({
        name,
        email,
        imageUrl,
        pdfUrl: imageUrl,
        downloadUrl,
      });

      res.json(normalizePdfRecord(saved));
    } catch (error) {
      if (fs.existsSync(filePath)) fs.unlinkSync(filePath);
      res.status(500).json({ error: error.message });
    }
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

router.get("/", async (req, res) => {
  try {
    const data = await UserPdf.find();
    res.json(data.map(normalizePdfRecord));
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

export default router;
